package com.rakesh.razorpay.common.enums;

public enum PaymentEvent {
    AUTHORIZE_ATTEMPTS,
    AUTHORIZE_SUCCESS,
    AUTHORIZE_FAILED,
    CAPTURE_ATTEMPTS,
    CAPTURE_SUCCESS,
    CAPTURE_FAILED,
    REFUND_ATTEMPTS,
    REFUND_SUCCESS,
    REFUND_FAILED,
    SETTLEMENT_ATTEMPTS,
    SETTLEMENT_SUCCESS,
    SETTLEMENT_FAILED,
    DISPUTE_ATTEMPTS,
    DISPUTE_SUCCESS,
    DISPUTE_FAILED
}
